name: linux

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qt
        uses: actions/cache@v2
        id: cache-qt
        with:
          path: /opt/qt512
          key: linux-qt-5.12

      - name: Install Qt
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.12.1-xenial
          sudo apt update
          sudo apt install qt512-meta-full
          
      - name: Test Qt
        run: |
          mkdir -p $HOME/.config/qtchooser/
          echo "/opt/qt512/bin" > $HOME/.config/qtchooser/default.conf
          echo "/opt/qt512/lib" >> $HOME/.config/qtchooser/default.conf
          export PATH="/opt/qt512/bin:$PATH"
          qmake -v

      - name: Cache Qt
        uses: actions/cache@v2
        id: cache-boost
        with:
          path: ${{runner.workspace}}/boost_1_73_0
          key: linux-boost-1.73.0

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2
          tar --bzip2 -xf ./boost_1_73_0.tar.bz2
          cd boost_1_73_0
          ./bootstrap.sh --prefix=${{runner.workspace}}/boost_1_73_0
          ./b2 install
