name: linux

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qt
        uses: actions/cache@v2
        id: cache-qt
        with:
          path: /opt/qt512
          key: linux-qt-5.12

      - name: Install Qt
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.12.1-xenial
          sudo apt update
          sudo apt install qt512-meta-full

